### ISSUE TITLE
The order number is not in sequence while we create new order manually.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/custom-order-numbers-for-woocommerce#107]
**Describe the bug**
The order number is not in sequence while we create new order manually.

**To Reproduce**
1. ORders are in sequence: 
![image](https://github.com/TycheSoftwares/custom-order-numbers-for-woocommerce/assets/15136179/936bbe99-db79-4984-be7e-c099fb5bd837)

2. Click on Add New Order button -
![image](https://github.com/TycheSoftwares/custom-order-numbers-for-woocommerce/assets/15136179/5fab99c7-44d1-498c-8373-0f51a7544c2c)

![image](https://github.com/TycheSoftwares/custom-order-numbers-for-woocommerce/assets/15136179/4872ab9f-509c-4748-8077-c2450fa62433)

I have tried with PHP 8.2.
Settings - 
https://prnt.sc/XxERjRiY6Dn- 
https://prnt.sc/hmS8AKL7S67x

**Additional context**
https://wordpress.org/support/topic/order-number-will-randomly-go-back-to-original-order-id/

**Comment by nidhitatosaniya** [comment]
Unable to replicate with latest copy. It's showing correctly see here: https://prnt.sc/hr7QP3ToxYH8. hence I closing it.
