### ISSUE TITLE
The blank automatic renewal orders are created due to our plugin.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/custom-order-numbers-for-woocommerce#126]
**Describe the bug**
Basically on renewal orders its creating empty orders. The version we are currently on I believe is the one directly from the Woo Commerce store. If we manually process the renewal it seems to work fine. Its on automated renewals where everything seems to break. I have gone through support with WooCommerce and other plugin companies trying to find the culprit and the last thing I could think is this plugin is causing ID issues on renewals.
I have create 2 subscription types using 2 different plugins. The reason I think its your plugin is how the orders are created. If you look the order numbers are completely out of wack. Both 8173 and 8172 are created using the automated renewal on WooSubscriptions.
![image](https://github.com/TycheSoftwares/custom-order-numbers-for-woocommerce/assets/15136179/8e6e08a3-7494-4d32-9fd2-5ba0cefe0215)

**To Reproduce**
I could replicate the issue on client's site by following the below steps:

1. Create an order for simple 1 day subscription product
2. Mark the subscription as "Active" and set Next Payment: to be renewed within 2-3 mins
![image](https://github.com/TycheSoftwares/custom-order-numbers-for-woocommerce/assets/15136179/0f566493-a3df-43e9-b7be-0971dbc56a15)

3. when our plugin is active, a blank order is created like as below:
![image](https://github.com/TycheSoftwares/custom-order-numbers-for-woocommerce/assets/15136179/82bf2dba-d1bb-44cb-b7cb-0b8f9e447c02)

When our Deactivated our plugin, it worked fine.

**Additional context**
https://support.tychesoftwares.com/conversation/671?folder_id=9

The plugin setup: 
![image](https://github.com/TycheSoftwares/custom-order-numbers-for-woocommerce/assets/15136179/a68b28d0-3098-4dcb-81af-4d2a1ddf0fbf)
![image](https://github.com/TycheSoftwares/custom-order-numbers-for-woocommerce/assets/15136179/5dad7a52-b9d7-4688-bec3-f765f2691bfc)

**Comment by gaminikhil** [comment]
This issue is not being replicated on our side. The client has not replied to anything about it, so I am closing this issue.
