### ISSUE TITLE
Critical error message comes when users have a large number orders & the plugin tries to update them.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/custom-order-numbers-for-woocommerce#60]
**Describe the bug**
Critical error message comes when users have a large number of orders & the plugin tries to update them.

**To Reproduce**
1. On woo_apeksha, I have 21000 plus past orders
2. Take the latest git copy 
3. Go to the plugin setting page, try to change the prefix
4. When I try to save that setting, the plugin throws me a critical error.

see the screenshot: https://www.screencast.com/t/TdzCNwr13M6e

**Expected behavior**
No critical error message should appear.

**Comment by ashokrane** [comment]
@apeksha10 I don't think there would be a real use case where a store that has 21000+ orders would want to update all the past orders too with the prefix/suffix. To avoid this, we should add the option of "Select orders to apply new settings to" to the Lite version too (which is already added in Pro). What do you think?

@upenkapse Please share your thoughts too.

**Comment by apeksha10** [comment]
@apeksha10 I don't think there would be a real use case where a store that has 21000+ orders would want to update all the past orders too with the prefix/suffix. To avoid this, we should add the option of "Select orders to apply new settings to" to the Lite version too (which is already added in Pro). What do you think?

That is good idea.

**Comment by mital-tyche** [comment]
Need to process based on batch wise in pro & lite both version. Hence I open this issue
