### ISSUE TITLE
Incompatible with ‘High-Performance order storage (COT)

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/custom-order-numbers-for-woocommerce#91]
I found incompatibility with HPOS for this plugin. I received the following notice from WP/Woocommerce when trying to update the tables in a staging environment:

![image](https://user-images.githubusercontent.com/15136179/232815742-1154ba5a-65e5-446c-900e-4a8ee217c404.png)

**Comment by nidhitatosaniya** [comment]
With latest copy I am unable to replicate this issue. Hanse I closing it. Attached screenshot :  https://app.screencast.com/9o6JTjovLJyh4
